---
name: Check Java Formatting

on:
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'adopt'
          java-version: 11
  
      - name: Checkstyle
        run: |
          mvn --no-transfer-progress jxr:jxr
          mvn --no-transfer-progress checkstyle:check
