---
name: Javadoc

on:
  pull_request:

jobs:
  javadoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Javadoc
        run: |
          mvn --no-transfer-progress javadoc:javadoc
